name: Run Jupyter Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - id: repo 
      name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install requests pandas matplotlib jupyter jupyterlab

        
    # Build the book
    - name: Run Script and Update Plot
      run: |
        jupyter nbconvert --to script course_scraper.ipynb
        python course_scraper.py


    # - name: Commit and Push Changes
    #   run: |
    #       git config --local user.email "actions@github.com"
    #       git config --local user.name "GitHub Actions"
    #       git add scraped_bsc_course.csv weather_locations.png
    #       git commit -m "Updated courses with GitHub Actions"
    #       git push origin main

  

