name: Run Jupyter Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - id: repo 
      name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install requests pandas matplotlib jupyter jupyterlab

        
    # Build the book
    - name: convert notebook to script and run
      run: |
        jupyter nbconvert --to script course_scraper.ipynb
        python course_scraper.py


   

